language: python
# command to install dependencies.
install: "pip install -r requirements.txt"
# variables de entorno
#env: DJANGO_SETTINGS_MODULE=myip.settings
# command to run tests
script: cd myip/ && ./manage.py test